/*
 * Author: Ireoluwa
 * Created on June 22, 2024, 11:25 AM
 * Purpose: sales prediction
 */

//System Libraries
#include <iostream>
using namespace std;

//User Libraries

//Global Constants - Mathematical, Scientific, Conversions

//Higher Dimensions go here. No Variables
const unsigned char PERCENT = 100;//Percent Conversion
//Function Prototypes

//Execution Begins here

int main(int argc, char** argv) {
    //Setting the random number seed
    
    //Declaring Variables
    float TotSls,        //Input -> total sales of the company in a a particular year
          ECSls,           //Output -> total sales of the East Coast division of the company
          ECPrcnt;       //Input -> percentage of the companys total sales generated by the East Coast
    
    //Initialize Variables
    TotSls = 8.6E6f; //$8.6 Million
    ECPrcnt = 58.0f / PERCENT;  
    
    //Processing/Mapping Inputs to Outputs
    ECSls = TotSls * ECPrcnt;
    
    //Displaying Input/Output Information
    cout << "If the company has $" << TotSls << " in sales this year,";
    cout << " the East Coast division will generate $" << ECSls << "." << endl;
    //Exiting stage left/right
    return 0;
}

